"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("./auth.routes"));
const organization_routes_1 = __importDefault(require("./organization.routes"));
const user_routes_1 = __importDefault(require("./user.routes"));
const wallet_routes_1 = __importDefault(require("./wallet.routes"));
const payment_routes_1 = __importDefault(require("./payment.routes"));
const article_routes_1 = __importDefault(require("./article.routes"));
const estamp_routes_1 = __importDefault(require("./estamp.routes"));
const order_routes_1 = __importDefault(require("./order.routes"));
const file_routes_1 = __importDefault(require("./file.routes"));
const notification_routes_1 = __importDefault(require("./notification.routes"));
const audit_routes_1 = __importDefault(require("./audit.routes"));
const settings_routes_1 = __importDefault(require("./settings.routes"));
const report_routes_1 = __importDefault(require("./report.routes"));
const estamp_provider_routes_1 = __importDefault(require("./estamp-provider.routes"));
const bulk_estamp_routes_1 = __importDefault(require("./bulk-estamp.routes"));
const policy_routes_1 = __importDefault(require("./policy.routes"));
const router = (0, express_1.Router)();
router.use("/auth", auth_routes_1.default);
router.use("/organizations", organization_routes_1.default);
router.use("/users", user_routes_1.default);
router.use("/wallet", wallet_routes_1.default);
router.use("/payments", payment_routes_1.default);
router.use("/articles", article_routes_1.default);
router.use("/estamps", estamp_routes_1.default);
router.use("/orders", order_routes_1.default);
router.use("/files", file_routes_1.default);
router.use("/notifications", notification_routes_1.default);
router.use("/audit", audit_routes_1.default);
router.use("/settings", settings_routes_1.default);
router.use("/reports", report_routes_1.default);
router.use("/estamp-provider", estamp_provider_routes_1.default);
router.use("/bulk-estamps", bulk_estamp_routes_1.default);
router.use("/policies", policy_routes_1.default);
exports.default = router;
